<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#In-this-notebook" data-toc-modified-id="In-this-notebook-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>In this notebook</a></span></li><li><span><a href="#Function-definition" data-toc-modified-id="Function-definition-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Function definition</a></span><ul class="toc-item"><li><span><a href="#Error-management" data-toc-modified-id="Error-management-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Error management</a></span></li><li><span><a href="#Testing-functions" data-toc-modified-id="Testing-functions-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Testing functions</a></span></li><li><span><a href="#Lambda-functions" data-toc-modified-id="Lambda-functions-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Lambda functions</a></span></li></ul></li><li><span><a href="#Packages" data-toc-modified-id="Packages-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Packages</a></span><ul class="toc-item"><li><span><a href="#Some-examples-with-numpy" data-toc-modified-id="Some-examples-with-numpy-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Some examples with numpy</a></span></li></ul></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Exercises</a></span></li></ul></div>

# More Python basics
**Camilo A. Garcia Trillos - 2020**

---

## In this notebook

- we look at how to define and test *functions*, and how to think in terms of error management.
- we discuss Python packages and start looking at some notable Python packages or libraries.

<a id="func_def"></a>
## Function definition

Python code is better structured by defining functions.

The basic syntaxis is  *def name_function: ---  return(---)*

Let us look at a first example: we will create a function that establishes if two integers are relative primes (i.e., that their maximum common divisor is 1). We will create several iterations of the function.

Let us start with a first simple implementation:



In [42]:
def rel_primes(x,y):
    # We can include a description of the function using a string immediately below the function
    ''' Receives two numbers and returns True if both are relative 
        primes or False otherwise
    
    '''
    
    z = min(x,y)                       # Assign to z the minimum from a and b
    for i in range(2,z) :               # run over all numbers between 2 and z (!)
        if (x%i)==0 and (y%i==0):      # if a number divides both a, b (i.e. the residual in both cases is zero) 
                                       # they are not relative primes ...
            return False               # ... in this case, return is False. This gets the flow out of the function
    return True                        # finally, if the program gets to this point, a,b are relative primes                      

# Note that the following line of code is outside the scope of the function
rel_primes(18,123) # This should be false, as 3 divides both


False

Check with other cases that the function works as it should. 

In Python, when the code within a function is executed, a new 'environment' is created. Every object/function that is defined within a function only lives within the function. So for example, tha variables x,y,z above are not accessible in the following line

In [43]:
# print(x,y,z) # this generates an error

However, functions *can* access variables and functions defined outside themselves. This is useful (as will be seen further below), but is sometimes a source of confusion (particualrly regarding variables). 

In the above definition of 'rel_prime, apart from the funcional part, we included a help description. At any point this information can be retrieved with *?* after the name of a function.

In [44]:
rel_primes?

What happens when we test the function with values that are not integers?

In [45]:
# rel_primes('a',1) # this gives an error

In [46]:
# rel_primes(1.2,1.4)

In [47]:
# rel_primes(3,4.2)

<a id="error_man"></a>
### Error management

Note that sometimes we get an error and sometimes we do not. Moreover, the error is not very informative of what happened. We can create our own error messages. In what follows we create a function that 'wraps' the previous one, while providing some error management.

In [48]:
def rel_primes2(a,b):
    
    # First we check if the inputs have the right type. Recall the type function we look at on the first notebook.
    
    if type(a)!=int:
        raise TypeError("Both numbers must be integers")

    if type(b)!=int:
        raise TypeError("Both numbers must be integers")
    
    # If no error is raised up to here, we call the original function.
        
    return rel_primes(a,b)  #Note that we can call functions we have defined before

print('This one works: 18 and 123 are both integers (and not relative primes)')
rel_primes2(18,123)


This one works: 18 and 123 are both integers (and not relative primes)


False

In [49]:
# rel_primes2('a',123) # Here we raise an error as we defined it

You can check that errors are raised in other cases (for example if you provide complex numbers or floats).

The other very common type of error to be raised is ValueError (i.e. raise ValueError(...)). This means that a given input has a value outside the accepted domain.

It is possible also to check if a call to a function produces an error using the keword 'try', so taht any error can be managed by the programmer. This can be useful when one wants to allow 

In [50]:
a=1.2
try:
    p=rel_primes2(a,1)
except:
    print('There would be an error because ',a,' is not integer.')
    print('But with try the error is caught here. We can then assign the value we want to p, for example -1')
    p=-1
    
p

There would be an error because  1.2  is not integer.
But with try the error is caught here. We can then assign the value we want to p, for example -1


-1

<a id="test_fun"></a>
### Testing functions

An important part of coding is testing. It entails designing a sequence of checks to evaluate the behaviour of a function.

The statement *assert* might be very useful for this purpose. It raises an error if a result is False.


In [51]:
#Some basic testing

assert rel_primes2(15,28),  'Failed with two large relative primes'
assert rel_primes2(2,3),  'Failed with two small relative primes'
assert not rel_primes2(15,25),  'Failed with two small numbers that are not relative primes'
# assert not rel_primes2(2,4),  'Failed with two small numbers that are not relative primes'

Note that we performed 4 tests. The last one fails and illustrates that the function defined above is not working properly. When the test fails, the associated fail message is displayed.

We proceed to fix the error (which is located on the rel_prime function). Run the code below and then run the tests again.

In [52]:
def rel_primes(a,b):
    # This is a corrected version
    ''' Receives two numbers and returns True if both are relative 
        primes or False otherwise
    
    '''
    
    for i in range(2,min(a,b)+1) :       # The error was here
        if (a%i)==0 and (b%i==0):                                             
            return False               
    return True                        

What happened? We have fixed the error on the rel_primes function (we were not including the las element in the cycle). Since the function rel_primes2 calls rel_prime, this one gets fixed as well. This helps it pass all the tests.

Note we have learnt something very important in addition: in jupyter, code depends on the order of *execution*, not the order in which the code is written.


**Remark:** In more professional settings, the preferred form of testing is via unittesting. If you want to learn more about it, read the [Python documentation on unittest](https://docs.python.org/3/library/unittest.html)


<a id="lambda_fun"></a>
### Lambda functions

We had seen that to define a function in Python, we use the command def followed by the name of the function, arguments and colon. There is an alternative in the form of lambda functions, that is useful to define inline functions.

The syntax is *name_function = lambda (vars): operations *


Here is an example where we implement the same function twice.


In [53]:
def square(x):
    return x*x

square2 = lambda y: y*y

In [54]:
assert square(100)==square2(100)

Lambda functions are very convenient for short tasks. In particular it is an easy way to encapsulate one line instructions in a function. Note, though that it is very hard 

Some final observations: 

- Functions are not forced to return a value (sometimes these are called *procedures*)
- More testing tools are provided on the [package](## 2. Packages) *unitest* 


<a id="packages"></a>
## Packages

Python comes with many functions already defined. Some of them come as part of the standard language (we have encountered some of them). However, the real power of Python comes from sets of functions put together in *packages*. 

Here are some of the ones we will use in this course (and are very useful in finance):

- **math** : some mathematical functions 
- **numpy** : vector and matrix capabilities and operations
- **scipy** : numerical scientific computing including integration, fixed points, solving ODEs, optimisation, …)
- **matplotlib** : plots
- **pandas** : database access and manipulation, and more plots routines
- **statutils**: Some statistical tools including test of hypothesis

Some packages we will not use but sare very useful in finance include:
- **keras**: Keras is a high-level neural networks library
- **sklearn**: A library with tools for data mining and data analysis


Here and in the nest notebook, we look at *numpy* and *math*. We will learn about the following packages while making applications ion finance.

Packages must be imported into the kernel we are excuting. By convention all imports should be done at the start of the program, and in the Jupyter case at the start of the notebook.

In [55]:
# By convention this should be placed at the top of the file. But it can be used anywhere 
import math           # import the math package
import numpy as np    # import the numpy package and create an alias for it 'np'
from math import sin, exp  # import only the functions sin and exp that are located on the math package

After running the above code, we can use **all** functions on the math package. Here are some examples:

In [56]:
x = sin(2*math.pi) # Note we can use the function sin, but the constant pi has to be called from the math package  as was not explicitly imported
y = math.log(exp(-5))
print(x,'\n',y)

-2.4492935982947064e-16 
 -5.0


### Some examples with numpy

Let us now look at numpy. Numpy is a scientific library taht has been optimised to perform vector and matrix operations.

We start by looking at how to create numpy objects. We can either transform another structure (for example a list) using the function *array*, or wwe can use one of the functions producing directly an array. Here are some examples:

In [57]:
a = np.array([3,4,5])  # an array with the numbers 3,4,5  
b = np.arange(3,6)     # an arary with the numbers 3,4,5
c = np.linspace(3,5,3) # an array with the numbers 3.,4.,5.

print('a:',a,' b:',b, 'c:',c)
print(type(a))
a

a: [3 4 5]  b: [3 4 5] c: [3. 4. 5.]
<class 'numpy.ndarray'>


array([3, 4, 5])

Note that the above objects are of class *array*, which was defined in the package numpy. Observe also how the result is printed if no print function is invoked. 

Let us look at some simple operations before arrays:

In [58]:
#Most operations are done piecewisely:
print('1. a==b:', a==b)
print('2. a+b:', a+b)
print('3. a*b:', a*b)
print('4. a/b:', a/b)
print('5. a^b:', a**b)
print('6. a==c:', a==c)

1. a==b: [ True  True  True]
2. a+b: [ 6  8 10]
3. a*b: [ 9 16 25]
4. a/b: [1. 1. 1.]
5. a^b: [  27  256 3125]
6. a==c: [ True  True  True]


Note the difference with respect to lists: the operator *+* means vector addition. Note also that most operations like '*' and '/' are defined pointwise.

Since operations are mostly pointwise, the sizes of vectors need to coincide or an error will be raised.

In [59]:
a2 = np.arange(10)
print(a2,b)
# a2*b # This raises an error

[0 1 2 3 4 5 6 7 8 9] [3 4 5]



We also have some vector and matrix operations. We can, for example, find the dot product of two vectors of the same size with the operator *@*

In [60]:
# Dot product of a and b
a_dot_b = a@b
# An alternative way of calculating it
a_dot_b2 = (a*b).sum()     # Sum is a method available for arrays
print(a_dot_b, a_dot_b2)


50 50


We will frequently make use of the possibility to generate (pseudo) random numbers following some given distributions. Numpy allows for this through its sub-module *random*. We can generate (pseudo-)random arrays and matrices of a given size. Here are some examples using the current prefered way of calling the generator function.

In [61]:
#Random numbers

#Initialise generator
rng = np.random.default_rng()

#Uniform random numbers
print('Uniform  2x2')
c = rng.random((2,2)) # This creates a matrix of 2 x 2 of independent U[0,1] random numbers
print(c)
print (c.shape)
print(c.size)

print("====")

print('Gaussian 5x3')
c = rng.standard_normal((5,3)) # This creates a matrix of 5 x 3 of independent standard Gaussian random numbers
print(c)
print (c.shape)
print(c.size)

Uniform  2x2
[[0.00402293 0.92855227]
 [0.20652578 0.25203236]]
(2, 2)
4
====
Gaussian 5x3
[[-0.27575154  0.53310893  0.44507331]
 [-0.68837963  0.22994042 -0.18444529]
 [ 0.28439512 -1.28905285  0.2785554 ]
 [ 0.44732293 -1.16586332 -0.48964622]
 [-0.9478309  -0.3861404   0.64377453]]
(5, 3)
15


This produces arrays in dimension 2 or matrices. We can also see the second use of operator '@': matrix (and matrix-vector) multiplication:

In [62]:
c@a # This is the result of multiplying the matrix c (Gaussian matrix) and the vector a

array([ 3.53054764, -2.06760363, -2.91024905, -5.76971558, -1.16918167])

The random generator can produce samples from different distributions: look at the help for rng.normal, rng.lognormal, rng.exponential....

In [63]:
rng.normal(5,25,30)

array([ 24.95271698,  13.73871573,   9.99159411,  20.79052055,
        31.85895662, -36.22206647, -11.07175789,  14.46314249,
        35.76367123, -13.32378492, -22.45700113,  13.28928144,
         0.35084196,  18.36771232,  19.612618  , -54.763979  ,
        23.37958481, -36.7965623 , -12.29178879,  11.63263464,
        40.88389568, -17.64077039,  32.51977919, -37.08901644,
        40.5043868 ,   7.56964159,  -8.72529758, -38.19203902,
        26.65609578,  -8.48852501])

**Remark:** Once imported, we can make use of numpy functions within our function definitions. We can also import a module *within* a function definition, however in that case, the imported modules are available only within that function.

<a id="exercises"></a>
## Exercises

1. Create a function that receives a positive integer $n$ and a probability $p \in (0,1)$, and returns the mean and standard deviation of a binomial distribution with these parameters.
Your function must raise errors whenever the probability is outside the given range and if that the number n is not and integer greater than 0.
Use the statement *assign* to test your function on some known cases.


In [64]:
import numpy as np

# def binomial_distribution(n,p):
#     a = np.random.binomial(n,p)
#     a_mean = a.mean()
#     a_std = a.std()
#
#     print(a_mean, a_std)
#
# def binomial_distribution2(n,p):
#     if type(n) != int or n <= 0:
#         raise TypeError("please enter a positive integer n")
#
#     if type(p) != float or p < 0 or p >1:
#         raise TypeError("please enter a valid possibility")
#     return binomial_distribution(n,p)
#
# binomial_distribution2(10,0.5)
import math

def binomial_distribution(n,p):
    return n*p, math.sqrt(n*p*(1-p))

def binomial_distribution2(n,p):
    if type(n) != int or n <= 0:
        raise TypeError("please enter a positive integer n")

    if type(p) != float or p < 0 or p >1:
        raise TypeError("please enter a valid possibility")
    return binomial_distribution(n,p)

assert binomial_distribution(100,0.5)==(50,5)
assert binomial_distribution(100,0.1)==(10,3)


2. Using np.rand, create a function that receives a positive integer $n$ and a probability $p \in (0,1)$, and returns an array with $n$ bernoulli trials with parameter $p$. 
Your function must raise errors whenever the probability is outside the given range and if that the number n is not and integer greater than 0.



In [65]:
import numpy as np

def bernoulli_distribution(n, p):
    rng = np.random.default_rng()
    a = rng.random(n)
    b = np.zeros(n)
    # print (b)
    for i in range(n):
        if a[i] <= p:
            b[i] = 1
        if a[i] > p:
            b[i] = 0

    mean = b.mean()
    std = b.std()
    # print ("list a:" + str(a))
    # print ("list b:" + str(b))

    # print(b)
    return 1.*b
#
# binomial_distribution(200,0.5)


def bernoulli_distribution2(n, p):
    if type(n) != int or n <= 0:
        raise TypeError("please enter a positive integer n")

    if type(p) != float or p < 0 or p >1:
        raise TypeError("please enter a valid possibility")
    return bernoulli_distribution(n,p)

bernoulli_distribution2(100,0.5)





array([1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1.])

3. Using the previous function, estimate the empirical mean and variance for n=[10,100,1000,10000]. Comment.

In [66]:
#set the value of p
p = 0.25

print( 'Calculation values:')
print(' \t\t Mean \t\t Var')
print(' \t\t', p, '\t\t', p*(1-p))


print('Enmpirical values')
print('n \t\t Mean \t\t Var')

for i in range(5):
    # aux = bernoulli_distribution2()
    # print(aux)
    # aux_mean = aux.mean()
    # aux_var = aux.var()
    aux_mean = bernoulli_distribution2(10**(i+1),p).mean()
    aux_var = bernoulli_distribution2(10**(i+1),p).var()

    print(10**(i+1),'\t\t',aux_mean,'\t\t',aux_var)



Calculation values:
 		 Mean 		 Var
 		 0.25 		 0.1875
Enmpirical values
n 		 Mean 		 Var
10 		 0.3 		 0.21000000000000002
100 		 0.24 		 0.1824
1000 		 0.239 		 0.18446400000000004
10000 		 0.2542 		 0.18819803999999996
100000 		 0.2489 		 0.18788440709999998
