 <h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#In-this-notebook" data-toc-modified-id="In-this-notebook-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>In this notebook</a></span></li><li><span><a href="#More-on-arrays" data-toc-modified-id="More-on-arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>More on arrays</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Some-canonical-matrices/vectors" data-toc-modified-id="Some-canonical-matrices/vectors-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Some canonical matrices/vectors</a></span></li><li><span><a href="#Inverting-a-matrix" data-toc-modified-id="Inverting-a-matrix-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Inverting a matrix</a></span></li><li><span><a href="#Solving-linear-systems" data-toc-modified-id="Solving-linear-systems-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Solving linear systems</a></span></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Exercises</a></span></li></ul></div>

# (More on) Numpy

**Camilo A. Garcia Trillos - 2020**

---

## In this notebook 

We learn more about the Numpy package: we look at arrays and matrices, and some of the associated modules.


We start by importing the modules we will use in this notebook: only numpy.

In [1]:
import numpy as np

<a id="arrays"></a>

## More on arrays

Let us look deeper at the numpy library. The numpy library contains useful tools to work with vectors and matrices, solve linear operations and generate random entries.


We have a look at data types and their implications, basic operations, some canonical matrices, matrix inversion and solution of linear systems.





In [2]:
a = np.array([1,3,6,1])

In [3]:
a

array([1, 3, 6, 1])

Two important methods for arrays are *size* and *shape*. The former give sus the total number of elements in an array. The latter tells us how these elements are organised, whcih is particularly useful to define matrices or higher order tensors.

In [4]:
a.size # The number of total elements in the array

4

In [5]:
a.shape

(4,)

This means that at this time, all elements are organised in a unique row. We can render this vector into a 'column vector' or into a 2x2 matrix *with the same entries* simply assigning the shape we want or by using the *reshape* method.

In [6]:
print('original')
print(a)
a.shape=(1,4)
print('column vector (inplace)')
print(a)
b = a.reshape(2,2)
print('matrix')
print(b)



original
[1 3 6 1]
column vector (inplace)
[[1 3 6 1]]
matrix
[[1 3]
 [6 1]]


When assigning the *shape* property, the array itself changes (this is called 'inplace'):

In [7]:
a

array([[1, 3, 6, 1]])

In [8]:
print(a[0,1]) # This is OK
print(a[0]) # this is OK
# a[1] #This is an error

3
[1 3 6 1]


The above error occurs because there is only one entry on the first dimension of the array.

Arrays, unlike lists, cannot in general combine different types of entries. The vector we created above was an integer vector (note the lack of dots at the end of all prints!). Hence, if we try to assign a float, we will get a roundup version of it

In [9]:
a[0,1] = 9.2

In [10]:
a

array([[1, 9, 6, 1]])

As mentioned above, 9.2 becomes 9. Let su try now by creating a vector of floats from the start:

In [11]:
b = np.array([1.0,3,6])

In [12]:
b

array([1., 3., 6.])

In [13]:
b[1] = 9.2

In [14]:
b

array([1. , 9.2, 6. ])

Note the difference!  The array b was initialized to have floats, thanks to writing 1.0 instead of 1.  Thus, in contrast to a, it contains 9.2 (instead of 9, as the array a does)

As *lists*, arrays are assigned by reference. What follows should not surprise you if you followed the first notebook.


In [15]:
c = b
c
c[0] = 7.1
print('c:',c)
print('b:', b)

c: [7.1 9.2 6. ]
b: [7.1 9.2 6. ]


If an independent copy of a given array is needed, we can use the method *copy*

In [16]:
c=b.copy()
c
c[1]=1
print(c)
print(b)

[7.1 1.  6. ]
[7.1 9.2 6. ]


In the previous notebook, we looked at the method *arange*. Here are ways to use it:

In [17]:
d = np.arange(3, 42, 7)
d

array([ 3, 10, 17, 24, 31, 38])

In [18]:
d = np.arange(38, 2, -7)
d

array([38, 31, 24, 17, 10,  3])

In [19]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a id="broadcasting"></a>
## Broadcasting

We mentioned in the previous notebook that there was an exception to the rule of operating with the exact same dimensions. This exception is called broadcasting. Let us first present an example: try to figure out what is happening

**Example 1**

In [20]:
d.shape = (5,2)
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
e = np.array([1,3])

In [22]:
print(d * e)
print(d.shape, e.shape)

[[ 0  3]
 [ 2  9]
 [ 4 15]
 [ 6 21]
 [ 8 27]]
(5, 2) (2,)


**Example 2**

In [23]:
e.shape = (1,2)
print(d * e)
print(d.shape, e.shape)

[[ 0  3]
 [ 2  9]
 [ 4 15]
 [ 6 21]
 [ 8 27]]
(5, 2) (1, 2)


**Example 3**

In [24]:
f = np.array([1,1,1,2,2]).reshape(-1,1)
print('f: ',f, 'and the shape of f:', f.shape)

f:  [[1]
 [1]
 [1]
 [2]
 [2]] and the shape of f: (5, 1)


In [25]:
print(f*d)
print(f.shape, d.shape)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [12 14]
 [16 18]]
(5, 1) (5, 2)


**Example 4**

However, recall that the following gives an error:

In [26]:
g = np.array([1,2,3])
print(d.shape,g.shape)
# print(g*d) # This gives an error

(5, 2) (3,)


If you have not figure it out, the explanation is as follows: suppose we are operating the arrays a and b. Suppose that the shape of a is $(m_1,m_2)$, while the shapes of b are $(n_1,n_2)$:
- If $n_i \neq m_i$  **and** both are different from one or empty for some $i=1, 2$, then the operation cannot be done.
- If $n_i \neq m_i$  **and** one of the two is equal to one or empty for some $i=1, 2$, then the operation is done by completing the missing dimensions via copying the remaining components.

Look again to the example to make sure you understand this process. In particular, see how the empty spaces can be accomodated to the above template.

**Note:** arrays can be *tensors*, i.e. have more than 2 dimensions. Broadcasting is generalised as you would expect.


**Example 5**

Observe the following example

In [27]:
d[0,0] = 1

In [28]:
d

array([[1, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
1/d

array([[1.        , 1.        ],
       [0.5       , 0.33333333],
       [0.25      , 0.2       ],
       [0.16666667, 0.14285714],
       [0.125     , 0.11111111]])

The above works, because 1 is taken as an array of empty size, so it can be broadcasted by repeating itself to operate on each entry.

Note though that the following is an error:

In [30]:
# d ** (-1) # This raises an error

What's wrong?  We initialized d with integers, and there is no well defined change of type for this operation.

In [31]:
d.dtype # Observe the type of this array

dtype('int64')

In [32]:
d = d.astype(float) # Set it to float

In [33]:
d.dtype # Observe again the type

dtype('float64')

In [34]:
d ** (-1) # The correct answer appears.

array([[1.        , 1.        ],
       [0.5       , 0.33333333],
       [0.25      , 0.2       ],
       [0.16666667, 0.14285714],
       [0.125     , 0.11111111]])

In [35]:
(d ** (-1)) == (1/d)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

<a id="canonical"></a>
## Some canonical matrices/vectors


Let us introduce some canonical matrices and vectors.

In [36]:
# Zeros and ones matrix/vector

print (np.zeros(10))
a = np.ones((2,5))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


By default these are float. If an integer is desired, this  has to be stated explicitly.

In [37]:
b=np.zeros(10, dtype=int)
print (b)

[0 0 0 0 0 0 0 0 0 0]


Some other useful functions are zeros_like and ones_like: they create zeros and ones of the lentgh and type of the parameter

In [38]:
print(np.zeros_like(a))
print(np.ones_like(b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1 1 1 1 1 1 1 1 1 1]


We have also an identity matrix and the function diag. Let us look at what they do:

In [39]:
c=np.eye(5)

In [40]:
c[2][2]=10
print(c)
print('=====')
print(np.diag(c))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
=====
[ 1.  1. 10.  1.  1.]


Diag can also be used to build a diagonal matrix, as shown below.

In [41]:
np.diag(np.arange(8))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])

<a id="inverting"></a>
## Inverting a matrix

Recall how to generate a random Gaussian matrix: here we generate a matrix of size 3x3, where each entry is i.i.d. with distribution $\mathcal N(0,1)$

In [42]:
rng = np.random.default_rng()
g = rng.standard_normal((3,3))
g

array([[ 1.98383875,  1.22518942, -1.74340608],
       [-2.21712834,  0.46381802, -1.11359998],
       [-0.42817125, -1.20089685, -1.53003983]])

We can check that the matrix is invertible, by looking at the rank of the matrix

In [43]:
np.linalg.matrix_rank(g)

3

If the rank is 3 then we can invert the matrix g.  We already showed that *g ** (-1)* does not give the matrix inverse. Instead it computes the reciprocals of each component:

In [44]:
g ** (-1)

array([[ 0.50407323,  0.81620032, -0.57358983],
       [-0.45103388,  2.156018  , -0.89798852],
       [-2.33551413, -0.83271099, -0.65357775]])

Instead the package numpy has a specific command to obtain the matrix inverse:

In [45]:
g_inv = np.linalg.inv(g)

In [46]:
g_inv

array([[ 0.1621881 , -0.3144152 ,  0.04403352],
       [ 0.23100224,  0.29964532, -0.48130495],
       [-0.22669616, -0.14719851, -0.28813386]])

Let's check:

In [47]:
g@g_inv

array([[ 1.00000000e+00, -1.34835727e-16,  4.12731285e-17],
       [-2.51480965e-17,  1.00000000e+00,  1.77787612e-17],
       [ 4.41314899e-17,  1.19457669e-16,  1.00000000e+00]])

Apart from rounding errors this is basically the identity matrix.

We need to be careful though:
- Inverting matrices is expensive
- Inversion is done numerically, and this algorithm is not *stable* when applied to certain matrices. 

Let us illustrate this point with an example. We are going to use another canonical matrix, the [Hilbert matrix](https://en.wikipedia.org/wiki/Hilbert_matrix). This matrix is famous for being ill conditioned (that is, there is a huge gap between its eigenvalues), which makes it a bad example for inversion algorithms.

In [48]:
from scipy.linalg import hilbert

dim = 13
ill_conditioned = hilbert(dim)
#ill_conditioned

In [49]:
np.linalg.cond(ill_conditioned)

4.7863923023780064e+17

In [50]:
ill_inverse = np.linalg.inv(ill_conditioned)
np.diag(ill_conditioned @ ill_inverse )   # If inverse is perfect, all entries here would be one (can you see why?)

array([1.        , 1.00000029, 1.0000776 , 1.00030518, 0.99238687,
       0.98805085, 0.94275134, 0.6014303 , 0.79631152, 0.60006177,
       1.08939814, 0.92097063, 1.01171875])

In [51]:
b = np.ones(dim)
ill_conditioned @ (ill_inverse @ b) # If inverse is perfect, all entries here would be one (can you see why?)

array([-0.82885124, -0.45175585, -0.28844112, -0.1791205 , -0.09182011,
       -0.01765168,  0.04692487,  0.1038551 ,  0.15445767,  0.19972684,
        0.24045054,  0.27726858,  0.31070785])

Note that the above tests show that we are not really getting a good approximation of the inverse.

There are several ways to account for this problem. One can add a small amount to the diagonal

In [52]:
ill_min = np.min(ill_conditioned)
ill_max = np.max(ill_conditioned)
print(ill_min,ill_max)

0.04 1.0


In [53]:
better_cond = ill_conditioned + np.diag (ill_min*0.05*np.ones(dim) )
better_inv = np.linalg.inv(better_cond)

In [54]:
ill_conditioned @ (better_inv @ b) # If inverse is perfect, all entries here would be one (can you see why?)

array([1.00160478, 0.99015151, 0.99379173, 1.00807935, 1.01921242,
       1.02373631, 1.02185175, 1.01473545, 1.00365078, 0.98968786,
       0.97371675, 0.95640769, 0.93826756])

Note that this solution is much closer to the one vector, and so the inverse is close to what we would like. 

But this solution has a *bias*, that is, we have a systematic error. A more expensive alternative is to add an error that is neglected in probability: we add  a small random amount to the matrix, and then average out a couple of solutions

In [55]:
noise_factor = np.diag(rng.random(dim) *0.02)

In [56]:
np.min(noise_factor), np.mean(noise_factor), np.max(noise_factor)

(0.0, 0.0007041062884113994, 0.019912364149678247)

In [57]:
better_cond2 = ill_conditioned + noise_factor
better_inv2 = np.linalg.inv(better_cond2)

In [58]:
ill_conditioned @ (better_inv2 @ b)

array([0.99978703, 0.98299876, 1.01352384, 1.0316158 , 1.03468996,
       1.02671412, 1.01144453, 0.99162023, 0.96911505, 0.94518493,
       0.92066456, 0.89610487, 0.87186566])

This works specially well when the matrix is a calculated covariance matrix: in this case one can randomly perturb the data before calculating the covariance.

<a id="lin_sys"></a>

## Solving linear systems

Sometimes we are not interested in finding the inverse matrix but rather in solving a liner system like

$$A {\bf x} ={\bf b}$$

Doing this directly is usually more efficient.

There is a whole theory on how to solve linear equations(this is at the core of numerical analysis), but we will simply use the predifined functions.

In [59]:
x = np.linalg.solve(ill_conditioned, b)
x

array([ 3.81427568e+00, -8.52406796e+02,  4.18627157e+04, -8.38422715e+05,
        8.74650261e+06, -5.38443457e+07,  2.09652792e+08, -5.35753454e+08,
        9.10436098e+08, -1.01878859e+09,  7.20893064e+08, -2.92250884e+08,
        5.17063946e+07])

We test it:

In [60]:
ill_conditioned @ x

array([1.        , 1.        , 1.00000001, 1.        , 1.        ,
       1.00000001, 1.        , 1.00000001, 1.        , 1.00000001,
       0.99999999, 1.        , 1.        ])

Very close to $b$ (a vector of ones). Compare with the result we obain using the inverse:

In [61]:
x2 = ill_inverse@b
ill_conditioned@x2

array([-0.82885124, -0.45175585, -0.28844112, -0.1791205 , -0.09182011,
       -0.01765168,  0.04692487,  0.1038551 ,  0.15445767,  0.19972684,
        0.24045054,  0.27726858,  0.31070785])

And compare with what we obtain using the modified inverse (with the small perturbation):

In [62]:
x3 = better_inv@b
ill_conditioned@x3

array([1.00160478, 0.99015151, 0.99379173, 1.00807935, 1.01921242,
       1.02373631, 1.02185175, 1.01473545, 1.00365078, 0.98968786,
       0.97371675, 0.95640769, 0.93826756])

Better... but solving the linear system is superior. 

**Remark:** Finding an inverse might be advantageous if several linear systems with the smae matrices have to be solved one after the other. 

<a id="exercises"></a>

## Exercises

1. Create a function  'special_gaussian(n)'  that generates a sample of $n$ independent Gaussians, where the variance of the $i$th component is $1/i$. (Note: You must use np.random.randn). Do not forget to avoid erros and test your function.

In [67]:
def special_gaussian2(n):
    variance = 1/ np.arange(1,n+1)
    return np.random.randn(n)*variance**0.5




def special_gaussian(n):
    print(type(n))
    if n <= 0 or type(n)!= int:
        raise TypeError ("Please entre a valid positive integer")
    return special_gaussian2(n)

special_gaussian(10)


<class 'int'>


array([ 0.00431777,  0.46070032, -0.75584664,  0.13589773, -0.62454832,
       -0.15900776,  0.41588751,  0.28553175,  0.26949862,  0.06578657])

2. We consider a one-period market model in a finite probability space. 

Create a function 'complete_market_1p(S0,S1)' that receives a vector S0 with the initial prices of the assets in a market, and a matrix S1 that gives the prices of each asset in the market under each scenario, and returns a boolean that states if the market is complete or not.

In [68]:
def complete_market_1p(S0, S1):
    return np.linalg.matrix_rank(S1.T) == S1.shape[1]

S0 = np.array([1,2])
S1 = np.array([[1,2,1],[3,2,1]])
complete_market_1p(S0,S1)

False